# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', django_markdown.models.MarkdownField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
