# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grantee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grantee',
        ),
    ]
