# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models
import iwg_blog.utils.models.fields
import meta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0007_auto_20160503_1129'),
        ('grantee', '0002_delete_grantee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to=b'images')),
                ('content', django_markdown.models.MarkdownField()),
                ('words_count', models.IntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[(b'draft', b'Draft'), (b'for_pub', b'Ready for publishing'), (b'published', b'Published')], default=b'draft', max_length=10)),
                ('hits', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(editable=False, null=True)),
                ('slug', iwg_blog.utils.models.fields.AutoSlugField(blank=True, editable=True, help_text=b'optional; will be automatically populated from `title` field', populate_from=b'title', unique=True)),
                ('short_description', django_markdown.models.MarkdownField()),
            ],
            options={
                'ordering': ['-published_at'],
                'abstract': False,
                'permissions': (('view_article_hits', 'Can view grantee hits'), ('change_article_slug', 'Can change grantee slug')),
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', iwg_blog.utils.models.fields.AutoSlugField(blank=True, editable=True, help_text=b'optional; will be automatically populated from `name` field', populate_from=b'name', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='grantee',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='grantee.Round'),
        ),
        migrations.AddField(
            model_name='grantee',
            name='tags',
            field=iwg_blog.utils.models.fields.OrderedManyToManyField(blank=True, related_name='grantees', to='blog.Tag'),
        ),
    ]
