# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grantee', '0003_auto_20160511_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantee',
            options={'ordering': ['-published_at'], 'permissions': (('view_grantee_hits', 'Can view grantee hits'), ('change_grantee_slug', 'Can change grantee slug'))},
        ),
    ]
