# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantee', '0004_auto_20160513_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantee',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grantee',
            name='title',
            field=models.CharField(max_length=130),
        ),
    ]
