# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grantee', '0005_auto_20160517_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='GranteeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to=b'documents')),
                ('file_preview', models.ImageField(blank=True, null=True, upload_to=b'documents/thumbnails')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='grantee.Grantee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
