# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grantee', '0006_granteedocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantee',
            name='tags',
        ),
    ]
