# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityTest',
            fields=[
                ('primary_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('last_access', models.DateTimeField(help_text=b'Datetime of last access to this model from the celery task')),
            ],
        ),
    ]
