# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleArticle',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('blog.article',),
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_sample',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[(b'draft', b'Draft'), (b'for_pub', b'Ready for publishing'), (b'published', b'Published')], default=b'draft', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='words_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'permissions': (('view_article_hits', 'Can view article hits'), ('change_article_slug', 'Can change article slug'))},
        ),
    ]
