# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subscriber'),
        ('blog', '0002_auto_20160421_1459'),
    ]

    operations = [
    ]
