# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:34
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


def forward(apps, schema_editor):
    Article = apps.get_model('blog', 'Article')
    Article.objects.filter(is_published=True).update(published_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(forward, reverse_code=migrations.RunPython.noop),
    ]
