# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160426_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'permissions': (('view_article_hits', 'Can view article hits'), ('change_article_slug', 'Can change article slug'))},
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
