# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160428_1320'),
        ('blog', '0005_auto_20160426_1342'),
    ]

    operations = [
    ]
