# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(max_length=300),
        ),
    ]
