# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_preview',
            field=models.ImageField(blank=True, null=True, upload_to=b'documents/thumbnails'),
        ),
    ]
