# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_document_file_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
