# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grantee', '0003_auto_20160511_1347'),
        ('attachments', '0003_document_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='grantee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='grantee.Grantee'),
        ),
    ]
