# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='article',
        ),
        migrations.RemoveField(
            model_name='document',
            name='grantee',
        ),
    ]
