# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0006_auto_20160527_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name=b'Visible'),
        ),
    ]
